### PR TITLE
DevEx: add entityName to all persisted entities 

### PR DESCRIPTION
**Pull request by rachaelparris**
Part of our elasticsearch refactoring:
https://trello.com/c/6i1I5Y50/478-elasticsearch-issues-hitting-field-mapping-limit

A lot of these do not get persisted, but for consistency I'm adding the field to all entities (open to other opinions on this!).

Update: after some discussion, we've decided to only add entityName to persisted entities. It can always be added to the others later if needed.

### CODE REVIEW

**Review by matthopson — COMMENTED** [review]
Do we need to add these to validation as well? (see User)

**Comment by rachaelparris** [comment]
> Do we need to add these to validation as well? (see User)

Yep, you're right. I'll add that in. Thanks!

**Review by kkoskelin — APPROVED** [review]

**Comment by kkoskelin** [comment]
question: is validation necessary strictly to make sure the entity name arrives in persistence? because of course the value gets set once in the constructors.

**Comment by rachaelparris** [comment]
> question: is validation necessary strictly to make sure the entity name arrives in persistence? because of course the value gets set once in the constructors.

None of the entities I updated in this PR are actually persisted. I'm honestly not sure if we even need to add the `entityName` on non-persisted entities, but I was doing it to be consistent (and the same with the validation). It's impossible to know from looking at our entities whether they're persisted or not, which is the reason I wanted this to just be consistent and always added to every entity.

**Review by kkoskelin — APPROVED** [review]
I'm still not entirely convinced of the need for validation, but no harm afaict.

**Pull request merged**
