### PR TITLE
7218 BUG: Migrated cases are Calendared and Blocked

### PR DESCRIPTION
**Pull request by mrinsin**
@matthopson @codyseibert Looks like 7219 will be fixed after the migration script written in this PR runs on prod, as no case that is `Calendared` will be able to be blocked.

### CODE REVIEW

**Comment by matthopson** [comment]
@mrinsin with 7219, I thought the issue was that the cases were being migrated in this state? How does the validation change reconcile that?

**Comment by mrinsin** [comment]
@matthopson the migration script that is a part of this PR will ensure that no calendared cases are blocked at all, and the functionality of removing a due date from an _non-calendared, blocked_ case works correctly, which is what made me, Rachael and Rae believe that the script will fix 7219!

**Comment by matthopson** [comment]
@mrinsin I guess the part I'm concerned about isn't really a concern anymore - essentially if I send a legacy case that is already in this state to the migrate case interactor it will fail validation. But we're not doing anymore legacy migrations, so we don't have to worry about that. Is that the thinking here?

**Comment by mrinsin** [comment]
@matthopson yes! Exactly that! :)

**Review by matthopson — APPROVED** [review]

**Review by rachaelparris — APPROVED** [review]

**Pull request merged**
