### PR TITLE
7010 Filter Records Bug

### PR DESCRIPTION
**Pull request by matthopson**
A tricky bug to track down - this is what appears to be happening.

When a WorkItem was deleted in dynamo (specifically inbox mapping records), we weren't actually seeing it get removed in ES. In `processStreamRecordsInteractor`, we do a couple of things with these events:
- We filter them to make sure we're processing records we want to process
- We call separate index/delete actions with groups of records.
The delete (REMOVE) events are processed first, followed by the indexing of other records. 

What we learned was, when deleting a record in dynamo, the event was fired off to ES as expected, BUT there was an update to that record in the global table that sets the `aws:rep:deleting` field to `true`. This was triggering a MODIFY event, which we'd process in the stream right AFTER processing the REMOVE event. So the record would just get added back.

We finally realized this was happening by logging the events in processStreamRecords, identify the conflicting REMOVE and MODIFY records, and doing a diff on the MODIFY record's NewImage and OldImage (effectively trying to work backwards from what had changed). That one `aws:rep:deleting` field was the only thing that was changing, which completely explained why we couldn't see find any other paths by which a race condition was being introduced in our code.

This PR filters out records where the `aws:rep:deleting` field is changed to `true`, effectively ignoring it in ES.

### CODE REVIEW

**Comment by waldoj** [comment]
I'm impressed as hell that y'all figured this out.

**Comment by matthopson** [comment]
@waldoj It almost took my sanity away...

**Comment by matthopson** [comment]
Also, 2/2 attempts to make a PR have failed... the bug just keeps on fighting, right from the grave.

**Comment by matthopson** [comment]
New PR: https://github.com/flexion/ef-cms/pull/7104

**Pull request closed without merging**
