### PR TITLE
3916 DoD

### PR DESCRIPTION
**Pull request by matthopson**

### CODE REVIEW

**Review by rachaelparris — APPROVED** [review]

**Comment by wbyoko** [comment]
tacked in a Sonarcloud Code Smell

**Review by wbyoko — APPROVED** [review]

**Comment by matthopson** [comment]
> tacked in a Sonarcloud Code Smell

Jinx, I guess

**Comment by wbyoko** [comment]
I actually didn't see that you already had that... oops

**Comment by matthopson** [comment]
> I actually didn't see that you already had that... oops

Extra non-smelly.

**Pull request merged**
