### PR TITLE
6281 - Sending a test email

### PR DESCRIPTION
**Pull request by codyseibert**

### CODE REVIEW

**Review by matthopson — APPROVED** [review]

**Review by kkoskelin — APPROVED** [review]

**Comment by kkoskelin** [comment]
I'm okay with this, but ... I'm not exactly sure what it is we are testing.  The host at `email.amazonwhatever` is a mail server that is expected to be fully functioning, right?  Are we simply trying to verify that the mail host is reachable?  And is that the equivalent of us making sure we have network connectivity and DNS?

**Comment by codyseibert** [comment]
We are testing that with the environment variables we have set in the lambda, we can successfully send off an email.  I guess it technically would verify that AWS SES service is running.

**Comment by kkoskelin** [comment]
In that case, I'm not sure if there's any utility in this. We can verify we generally have network connectivity, I guess.  But AWS SES is not a service that is our responsibility.  I need a stronger argument for why this is useful.

**Comment by matthopson** [comment]
> I need a stronger argument for why this is useful.

See AC for story? This was groomed by the team + the court's tech lead and PO. Also, it _is_ testing our internal config, which is probably useful.

**Review by rachelschneiderman — APPROVED** [review]

**Review by sutt0n — APPROVED** [review]
Looks good! If the status fails on deployed envs, we can probably switch `test@example.com` to using `success@simulator.amazonses.com` to avoid that whole "can't send email to unverified address" via the AWS Sandbox mode -- if it even arises. 🤷‍♂️ 

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-simulator.html#send-email-simulator-considerations

**Review by rachelschneiderman — APPROVED** [review]

**Review by kkoskelin — APPROVED** [review]
I think this is quite excellent.

**Pull request merged**
