### PR TITLE
Taxpayer view updates

### PR DESCRIPTION
**Pull request by kkoskelin**
remove status column; provide “Back to dashboard” link at the top of taxpayer case detail view
(p.s. branch name should have been "111-taxpayer-updates)

### CODE REVIEW

**Comment by kkoskelin** [comment]
screen shot 2018-12-06 at 1 57 23 pm

**Comment by kkoskelin** [comment]
screen shot 2018-12-06 at 1 56 19 pm

**Review by ericsorenson — CHANGES_REQUESTED** [review]
the back to dashboard link should be right under the header, like the petitions clerk view 
image

**Comment by kkoskelin** [comment]
Updated screenshot:
screen shot 2018-12-06 at 3 18 39 pm

**Review by ericsorenson — APPROVED** [review]

**Review by sadlerw — APPROVED** [review]

**Pull request merged**
