### PR TITLE
1889: refactor case detail helper

### PR DESCRIPTION
**Pull request by rachaelparris**
Also fixed some incorrect logic from #2124.

### CODE REVIEW

**Review by kkoskelin — APPROVED** [review]

**Review by wbyoko — CHANGES_REQUESTED** [review]
I don't think we should be using one word variables.

**Comment by rachaelparris** [comment]
> I don't think we should be using one word variables.

Are you talking about `associated`? What would you suggest instead? `isAssociated`?

**Comment by wbyoko** [comment]
`isAssociated` works. mostly for refactoring and clarity. one word variables are more difficult to track down and generally too generic. usually 'is' or 'has' is tacked on for one word booleans.

**Review by wbyoko — APPROVED** [review]

**Pull request merged**
