### PR TITLE
Devex 390: Consolidate `shared/src/utilities` `shared/src/business/utilities`

### PR DESCRIPTION
**Pull request by rachelschneiderman**
Obviously I took some creative liberties here with file placement, please feel free to nitpick! I'm happy to change or move things around 😄

### CODE REVIEW

**Review by kkoskelin — APPROVED** [review]
Awesome.

**Comment by kkoskelin** [comment]
Oh, one other thought about this... obviously when we're refactoring by moving a file, we end up fixing paths all over the place and it can be really tedious.  Better IDEs would help this, of course, but so far my search for vscode tooling that helps hasn't turned up much that is reliable.
One thing that I tried to do quite a while ago was to use path aliases in the package.json so that we could write something like `@entities/Case` instead of figuring out how many dot-dot paths.  I got hung up when I couldn't get `jest` to play nice, even when I tried to write my own little jest plugin -- because jest uses its own resolver.  If you find a way to make that work with webpack and testing frameworks, that'd be cool, too. :)

**Comment by rachelschneiderman** [comment]
> Oh, one other thought about this... obviously when we're refactoring by moving a file, we end up fixing paths all over the place and it can be really tedious. Better IDEs would help this, of course, but so far my search for vscode tooling that helps hasn't turned up much that is reliable. One thing that I tried to do quite a while ago was to use path aliases in the package.json so that we could write something like `@entities/Case` instead of figuring out how many dot-dot paths. I got hung up when I couldn't get `jest` to play nice, even when I tried to write my own little jest plugin -- because jest uses its own resolver. If you find a way to make that work with webpack and testing frameworks, that'd be cool, too. :)

This is a great idea! Should I add it as another devex card?

**Comment by kkoskelin** [comment]
> This is a great idea! Should I add it as another devex card?

By all means!  I feel like I'd tried it as a devex once and gave up on it, but seems like maybe it's possible if the right (determined) developer gives it a go. :)

**Pull request merged**
