### PR TITLE
482 validation messages

### PR DESCRIPTION
**Pull request by matthopson**

### CODE REVIEW

**Comment by wbyoko** [comment]
Could we get a screenshot?

**Comment by matthopson** [comment]
Screen Shot 2019-12-13 at 10 07 03 AM

**Comment by wbyoko** [comment]
of multiple messages displaying on the modal?

**Comment by matthopson** [comment]
Screen Shot 2019-12-13 at 10 09 12 AM

**Review by wbyoko — APPROVED** [review]

**Pull request merged**
