### PR TITLE
8545 logging order search

### PR DESCRIPTION
**Pull request by codyseibert**

### CODE REVIEW

**Review by matthopson — APPROVED** [review]
Just confirming we want the raw search results, and not what's filtered for that given user / role?

**Comment by codyseibert** [comment]
@matthopson @kkoskelin ^ any comments?

**Review by kkoskelin — APPROVED** [review]

**Comment by kkoskelin** [comment]
> Just confirming we want the raw search results, and not what's filtered for that given user / role?

I think that's right, but should check with cholly probably.

**Comment by kkoskelin** [comment]
I've confirmed with @cholly75 that capturing the results size *prior* to any permissions-based filtering is indeed what he's looking for.  We're in the clear.

**Pull request merged**
