### PR TITLE
980: generate filing document titles

### PR DESCRIPTION
**Pull request by kkoskelin**
Cover all scenarios, tests
Removing unneeded CSV file

### CODE REVIEW

**Review by rachaelparris — APPROVED** [review]

**Review by wbyoko — COMMENTED** [review]
Non standard D should have a date field

**Comment by kkoskelin** [comment]
> Non standard D should have a date field

I think in this case, this is more about driving the UI; by the time the information is handed to the document generation code, the date-to-string formatting likely should have already occurred.

**Comment by wbyoko** [comment]
Okay. I was just thinking we would not want to use `userText` as the property.

**Comment by kkoskelin** [comment]
I'm definitely open to rewiring if we get closer connecting this code to the data from the UI.

**Review by wbyoko — APPROVED** [review]

**Pull request merged**
